### ISSUE TITLE
libcurl.so.4: undefined symbol: libssh2_scp_recv2

### ISSUE THREAD

**Issue by xigrug** [conda-forge/gmt-feedstock#37]
>>> import gmt
Traceback (most recent call last):
  File "/data/c03n02/cliu/study/python/gmt-python/gmt-python-master/gmt/clib/utils.py", line 159, in load_libgmt
    libgmt = ctypes.CDLL('.'.join([libname, clib_extension()]))
  File "/users1j/cliu/soft/anaconda2/envs/python3.6/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /users1j/cliu/soft/anaconda2/envs/python3.6/lib/python3.6/lib-dynload/../.././libcurl.so.4: undefined symbol: libssh2_scp_recv2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/c03n02/cliu/study/python/gmt-python/gmt-python-master/gmt/__init__.py", line 27, in <module>
    _begin()
  File "/data/c03n02/cliu/study/python/gmt-python/gmt-python-master/gmt/session_management.py", line 17, in begin
    with LibGMT() as lib:
  File "/data/c03n02/cliu/study/python/gmt-python/gmt-python-master/gmt/clib/core.py", line 103, in __init__
    self._bind_clib_functions(libname)
  File "/data/c03n02/cliu/study/python/gmt-python/gmt-python-master/gmt/clib/core.py", line 136, in _bind_clib_functions
    self._libgmt = load_libgmt(libname)
  File "/data/c03n02/cliu/study/python/gmt-python/gmt-python-master/gmt/clib/utils.py", line 168, in load_libgmt
    raise GMTCLibNotFoundError(msg)
gmt.exceptions.GMTCLibNotFoundError: Couldn't find the GMT shared library 'libgmt'. Have you tried setting the LD_LIBRARY_PATH environment variable?
Original error message:

    /users1j/cliu/soft/anaconda2/envs/python3.6/lib/python3.6/lib-dynload/../.././libcurl.so.4: undefined symbol: libssh2_scp_recv2

**Comment by leouieda** [comment]
Hi @xigrug, could you please tell us in detail how you installed GMT and which version?

**Comment by ocefpaf** [comment]
This is a known problem with `curl`. See https://github.com/conda-forge/curl-feedstock/issues/23

I'm closing this b/c it is not a `gmt` issue. @xigrug if you have any suggestion on how to fix that for OS X user please comment on https://github.com/conda-forge/curl-feedstock/issues/23
