### ISSUE TITLE
OSX build failing on upload_or_check_non_existence

### ISSUE THREAD

**Issue by leouieda** [conda-forge/gmt-feedstock#53]
Issue: 

The OSX build of the `deploy` branch fails on the last step:

```
$ upload_or_check_non_existence ./recipe conda-forge --channel=dev -m ./.ci_support/${CONFIG}.yaml
Adding in variants from internal_defaults
Adding in variants from ./.ci_support/osx_.yaml
Attempting to finalize metadata for gmt
Solving environment: ...working... done
Solving environment: ...working... done
Solving environment: ...working... done
Traceback (most recent call last):
  File "/Users/travis/miniconda3/bin/upload_or_check_non_existence", line 146, in <module>
    main()
  File "/Users/travis/miniconda3/bin/upload_or_check_non_existence", line 138, in main
    upload(token_fn, path, owner, channel)
  File "/Users/travis/miniconda3/bin/upload_or_check_non_existence", line 67, in upload
    env=os.environ)
  File "/Users/travis/miniconda3/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['anaconda', '--quiet', '-t', '/var/folders/vy/rcv48w3j4w79llzf_x6qnvw40000gn/T/tmp_fsf7ymx/binstar.token', 'upload', '/Users/travis/miniconda3/conda-bld/osx-64/gmt-6.0.0a17-blas_openblash0670df6_200.tar.bz2', '--user=conda-forge', '--channel=dev']' returned non-zero exit status 1.

```

The recipe was rerendered recently `conda smithy` says that there is nothing to be done. Any ideas @ocefpaf?

**Comment by ocefpaf** [comment]
#54 did not work :-/

@isuruf I'm probably missing something obvious here, can you take a quick look?

**Comment by ocefpaf** [comment]
I guess I forgot to push the re-render... I was going to use the web-services and forgot that too.

**Comment by ocefpaf** [comment]
:tada:

https://anaconda.org/conda-forge/gmt/6.0.0a17/download/osx-64/gmt-6.0.0a17-blas_openblash0670df6_200.tar.bz2

**Comment by ocefpaf** [comment]
Hehe. This is an internal problem that there is no way the maintainers could know.

@isuruf we shoulf probably expect a few more feedstock that are using branches to suffer from the same problem, but I don't think there are many of those out there though.
